### ISSUE TITLE
[BUG] Current Windows release does not replace textures

### ISSUE THREAD

**Issue by Skyluker4** [Skyluker4/UnityAssetReplacer#15]
## Description

Can't replace textures on the Windows releases found on this page.

## Steps to Reproduce

1. Run 'UnityAssetReplacer' with options ```./UnityAssetReplacer -b assetbundle -t -i input_folder -o output_assetbundle```

## Expected Behavior

Expected program to replace textures successfully.

## Output

```
Unhandled exception. System.DllNotFoundException: Unable to load DLL 'textoolwrap' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at TexturePlugin.PInvoke.EncodeByPVRTexLib(IntPtr data, IntPtr buf, Int32 mode, Int32 level, UInt32 width, UInt32 height)
   at TexturePlugin.TextureEncoderDecoder.EncodePVRTexLib(Byte[] data, Int32 width, Int32 height, TextureFormat format, Int32 quality)
   at TexturePlugin.TextureEncoderDecoder.Encode(Byte[] data, Int32 width, Int32 height, TextureFormat format, Int32 quality)
   at TexturePlugin.TextureImportExport.ImportPng(String file, TextureFormat format, Int32& width, Int32& height)
   at UnityAssetReplacer.TextureAsset.<Replace>b__4_0(List`1 assetReplacers, String inputFileName, String inputFilePath)
   at UnityAssetReplacer.Asset.ReplaceAll(String& inputDirectory, String& outputAssetBundlePath, Action`3 operation)
   at UnityAssetReplacer.TextureAsset.Replace(String& inputDirectory, String& outputAssetBundlePath)
   at UnityAssetReplacer.Program.RunOperation(Asset uar, Boolean dump, Boolean replace)
   at UnityAssetReplacer.Program.Main(String[] args)
```

## Platform

- Operating System: Windows
- Architecture:  x64, x86
- Program Version: 3.0.1

**Comment by Skyluker4** [comment]
Need to fix Build workflow for Windows. Building on ```ubuntu-latest``` does not include ```TexToolWrap``` on Windows only for some reason.

**Comment by Skyluker4** [comment]
For now, build from source on Windows if you need to replace textures.
