### ISSUE TITLE
[BUG] Program crashes when attempting to import moddified assets back into the bundle file

### ISSUE THREAD

**Issue by FaustBaudelaire** [Skyluker4/UnityAssetReplacer#35]
## Description
A null reference exception error causing the process of importing modified assets back into a bundle to crash and abort.

## Steps to Reproduce
1. _Run 'UnityAssetReplacer' with options '-t -b "/path/to/decompressed/bundle" -i "/path/to/folder/of/moddified/assets/" -o "/path/to/output/new/bundle/file" ' 
2. _See the error._

## Expected Behavior
I expect to have a new .bundle file with my moddified assets in it.

## Output
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at AssetsTools.NET.Extra.BundleFileInstance..ctor(FileStream stream, String root, Boolean unpackIfPacked)
   at AssetsTools.NET.Extra.AssetsManager.LoadBundleFile(FileStream stream, Boolean unpackIfPacked)
   at AssetsTools.NET.Extra.AssetsManager.LoadBundleFile(String path, Boolean unpackIfPacked)
   at UnityAssetReplacer.Asset..ctor(String& inputAssetBundlePath)
   at UnityAssetReplacer.TextureAsset..ctor(String& inputAssetBundlePath)
   at UnityAssetReplacer.Program.Main(String[] args)
Aborted (core dumped)

## Platform
- Operating System: Linux (Arch)
- Architecture: x64
- Program Version: v3.0.1 

## Extra information
I know having the modified assets being in the exact same order as in the original file is a requirement, and I have made sure that they're in fact in the same order.

**Comment by lattaai12** [comment]
Hello, I tried to solve the issue.

This is what I did:

The null reference exception is likely occurring because the AssetsManager.LoadBundleFile method is returning null. We'll add a null check and throw a more informative exception to handle this case.

You can review changes in this commit: https://github.com/lattaai12/Skyluker4-UnityAssetReplacer-35/commit/99b325efd8cc3679ad2bbd076c7581caed3fa636.


> [!CAUTION]
> Disclaimer: The commit was created by Latta AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---
This issue was tried to solve for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
